# Auto-generated by the bump-tap workflow — do not edit by hand.
# Source template: .github/templates/charter.rb.tmpl in Servant-Software-LLC/Charter.
# Placeholders (0.2.0, @SHA_*@) are substituted per release from the release checksums.
class Charter < Formula
  desc "Visual, reviewable plans your agent drafts and you annotate in place"
  homepage "https://github.com/Servant-Software-LLC/Charter"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-osx-arm64.tar.gz"
      sha256 "831be6584fe67fffd9c9e864b46380fd3d520ec177483db6e6726ab2f9c09763"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-osx-x64.tar.gz"
      sha256 "e177aa1e3ad47251596abda095f9896cc63127b623c4757848e2d9352b6f85a4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-linux-arm64.tar.gz"
      sha256 "4e82a077cb5a4be7a4bfe2f123c82bfb092e1eb1880ee7d94fd594fc543fa0a0"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-linux-x64.tar.gz"
      sha256 "0a6d5335e254fd404d773d78dcde12ddb0143435cc93e38e6aef69a201b460b0"
    end
  end

  # Single self-contained binary — no sibling assets yet, so install it straight into bin.
  def install
    bin.install "charter"
  end

  test do
    assert_match "charter", shell_output("#{bin}/charter --version")
  end
end
