# Auto-generated by the bump-tap workflow — do not edit by hand.
# Source template: .github/templates/charter.rb.tmpl in Servant-Software-LLC/Charter.
# Placeholders (0.12.0, @SHA_*@) are substituted per release from the release checksums.
class Charter < Formula
  desc "Visual, reviewable plans your agent drafts and you annotate in place"
  homepage "https://github.com/Servant-Software-LLC/Charter"
  version "0.12.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-osx-arm64.tar.gz"
      sha256 "1593c6d1144cb034bc1896c3e9bc19cdb75c5cbaa95812a57aabdd0618aa4362"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-osx-x64.tar.gz"
      sha256 "5e7b5c2181f14f5f69a18d19f8827dd0f0a5f74a82dab33a6931d3c7659549fb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-linux-arm64.tar.gz"
      sha256 "a0f836d453077bab18f7179c414c9ecb404bb73aecce88060d69aa84956231f0"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-linux-x64.tar.gz"
      sha256 "6ff273e5658a42b631c652148b13897d2b58d82e205bda7a82328dc8609cbfb0"
    end
  end

  # Single self-contained binary — no sibling assets yet, so install it straight into bin.
  def install
    bin.install "charter"
  end

  test do
    assert_match "charter", shell_output("#{bin}/charter --version")
  end
end
