# Auto-generated by the bump-tap workflow — do not edit by hand.
# Source template: .github/templates/charter.rb.tmpl in Servant-Software-LLC/Charter.
# Placeholders (0.24.0, @SHA_*@) are substituted per release from the release checksums.
class Charter < Formula
  desc "Visual, reviewable plans your agent drafts and you annotate in place"
  homepage "https://github.com/Servant-Software-LLC/Charter"
  version "0.24.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-osx-arm64.tar.gz"
      sha256 "0d50f5befba595e2ea3aae0eb04f3fdcba20b41d85cd0132970c3cccb029bc0e"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-osx-x64.tar.gz"
      sha256 "f5da0554b47a1a7aa289fe2ab872a13567b1ae36da7753efbb8fd12f3699fcce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-linux-arm64.tar.gz"
      sha256 "61224f91d5f156655b3028971a3336e7a7c59daedab65235463006a3beb2287f"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Charter/releases/download/v#{version}/charter-#{version}-linux-x64.tar.gz"
      sha256 "c746b4a94228d9409537b4f3d88a44b056629939b2f118f77f8e25d73bc3feaa"
    end
  end

  # Single self-contained binary — no sibling assets yet, so install it straight into bin.
  def install
    bin.install "charter"
  end

  test do
    assert_match "charter", shell_output("#{bin}/charter --version")
  end
end
