# Auto-generated by the bump-tap workflow — do not edit by hand.
# Source template: .github/templates/guardrails.rb.tmpl in Servant-Software-LLC/Guardrails.
# Placeholders (1.10.0, @SHA_*@) are substituted per release from the release checksums.
class Guardrails < Formula
  desc "Ship AI-built software with confidence — verify agentic work against your standards"
  homepage "https://github.com/Servant-Software-LLC/Guardrails"
  version "1.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-osx-arm64.tar.gz"
      sha256 "1954a3d88afe6c2093a6558ef444de7af3f4c93f29d54d802ca1ef24240e8d16"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-osx-x64.tar.gz"
      sha256 "1f01ca9d2aa1f1282f0adc9e475401646adad1abace984cc8100565f9bd6c6c8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-linux-arm64.tar.gz"
      sha256 "664439fb17ef067bae69d07673d7ccd86b29e6460fde76e3ed1e3d34bcd6a785"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-linux-x64.tar.gz"
      sha256 "0ff6f280187e65cbff2510112e89e3e5dbcd058cd962089ebdfc39dd8afe8163"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"guardrails").write <<~SH
      #!/bin/bash
      exec "#{libexec}/guardrails" "$@"
    SH
    chmod 0755, bin/"guardrails"
  end

  def caveats
    <<~EOS
      Guardrails ships agent-side skills. To deploy them for Claude Code, run:
        guardrails skills install --force
      then restart Claude Code so it picks them up.
    EOS
  end

  test do
    # `guardrails --version` prints the BARE version (e.g. "1.1.0"), not the tool
    # name — asserting on "guardrails" here could never match. Pin it to the formula's own
    # version so `brew test` proves the installed binary is the one this formula declares.
    assert_match version.to_s, shell_output("#{bin}/guardrails --version")
  end
end
