# Auto-generated by the bump-tap workflow — do not edit by hand.
# Source template: .github/templates/guardrails.rb.tmpl in Servant-Software-LLC/Guardrails.
# Placeholders (1.19.0, @SHA_*@) are substituted per release from the release checksums.
class Guardrails < Formula
  desc "Ship AI-built software with confidence — verify agentic work against your standards"
  homepage "https://github.com/Servant-Software-LLC/Guardrails"
  version "1.19.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-osx-arm64.tar.gz"
      sha256 "7b8d9e3d9ac185ff59a1d9522da407dc6d9e112d75ddbfb221528cbf6e863f47"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-osx-x64.tar.gz"
      sha256 "50607fb3f19592f842e7945c1091947fa6ce3a57b09a25cfb7f4a71c4527d6ba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-linux-arm64.tar.gz"
      sha256 "9c132306ec480ef318c9ebff99a056cffe17b5146802063d24e8fdadd45280bb"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-linux-x64.tar.gz"
      sha256 "3498b181b8227db1a9be43c9f69898faa32589fd49ecfd2b544843241817b746"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"guardrails").write <<~SH
      #!/bin/bash
      exec "#{libexec}/guardrails" "$@"
    SH
    chmod 0755, bin/"guardrails"
  end

  def caveats
    <<~EOS
      Guardrails ships agent-side skills. To deploy them for Claude Code, run:
        guardrails skills install --force
      then restart Claude Code so it picks them up.
    EOS
  end

  test do
    # `guardrails --version` prints the BARE version (e.g. "1.1.0"), not the tool
    # name — asserting on "guardrails" here could never match. Pin it to the formula's own
    # version so `brew test` proves the installed binary is the one this formula declares.
    assert_match version.to_s, shell_output("#{bin}/guardrails --version")
  end
end
