# Auto-generated by the bump-tap workflow — do not edit by hand.
# Source template: .github/templates/guardrails.rb.tmpl in Servant-Software-LLC/Guardrails.
# Placeholders (1.6.0, @SHA_*@) are substituted per release from the release checksums.
class Guardrails < Formula
  desc "Ship AI-built software with confidence — verify agentic work against your standards"
  homepage "https://github.com/Servant-Software-LLC/Guardrails"
  version "1.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-osx-arm64.tar.gz"
      sha256 "29c980619916c60367b95b89c04502b3c8fb12a0e85e923f190b09b9ee69dcdd"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-osx-x64.tar.gz"
      sha256 "0b9c6867c9510b811840a1f34c9724d61ee17ec6017be8a87a2c12293a48cd74"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-linux-arm64.tar.gz"
      sha256 "b9087348f48c8f2561a5a9e85d1fc68267fbd1f4299f6019a12765abdafceb11"
    end
    on_intel do
      url "https://github.com/Servant-Software-LLC/Guardrails/releases/download/v#{version}/guardrails-#{version}-linux-x64.tar.gz"
      sha256 "d8e95c2d30074ddefb44fa9028e6a2f8aa64a982ddb4a01bd369c5b39859e894"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"guardrails").write <<~SH
      #!/bin/bash
      exec "#{libexec}/guardrails" "$@"
    SH
    chmod 0755, bin/"guardrails"
  end

  def caveats
    <<~EOS
      Guardrails ships agent-side skills. To deploy them for Claude Code, run:
        guardrails skills install --force
      then restart Claude Code so it picks them up.
    EOS
  end

  test do
    # `guardrails --version` prints the BARE version (e.g. "1.1.0"), not the tool
    # name — asserting on "guardrails" here could never match. Pin it to the formula's own
    # version so `brew test` proves the installed binary is the one this formula declares.
    assert_match version.to_s, shell_output("#{bin}/guardrails --version")
  end
end
